#!/bin/sh

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid '#222E45' 
vncconfig -iconic &
xterm -geometry 110x24+10+10 -ls -title "Welcome to Appion-Protomo 1" &
xterm -geometry 110x24+10-100 -ls -title "Welcome to Appion-Protomo 2" &
exec fluxbox
