#!/bin/sh

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid '#222E45' 
vncconfig -iconic &
firefox -new-tab -url 0.0.0.0/myamiweb/ -new-tab -url https://github.com/nysbc/appion-protomo -new-tab -url https://groups.google.com/forum/#!forum/appion-protomo &
xterm -geometry 110x24+10+10 -ls -title "Welcome to Appion-Protomo!" &
xterm -geometry 110x24+10-100 -ls -title "Try using 'screen' to run virtual terminals!" &
xterm -geometry 110x24+800+10 -ls -title "First follow the example on github" &
xterm -geometry 110x24+800-100 -ls -title "Get assistance at the Appion-Protomo google group" &
exec fluxbox
